#!/bin/bash

if [ -z "$1" ]
  then
    echo "Need a target directory"
    exit 1
fi

if [ -z "$2" ]
  then
    echo "Need a REGEX"
    exit 1
fi

DIRECTORY=$1
RE=$2

echo "Listing items in $DIRECTORY and spotting REGEX $RE"

ls $DIRECTORY |
while read -r line
  do
  if echo $line | grep -q "$RE"
    then
    echo "$line matches the REGEX $RE"
  else
    echo "$line does not match the REGEX"
  fi
done
