#!/bin/bash

if [ -z "$1" ]
  then
    echo "Need a target directory"
    exit 1
fi

if [ -z "$2" ]
  then
    echo "Need a REGEX"
    exit 1
fi

if [ -z "$3" ]
  then
    echo "Need a rename REGEX"
    exit 1
fi

DIRECTORY=$1
RE=$2
SUB=$3

echo "Listing items in $DIRECTORY and spotting REGEX $RE to rename using $SUB"

ls "$DIRECTORY" |
while read -r line
  do
  if echo "$line" | grep -q "$RE"
    then
    echo "$line matches the REGEX $RE"
    new="$(echo "$line" | sed "$SUB")"
    echo "$line becomes $new"
  else
    echo "$line doesn't match"
  fi
done

